### ISSUE TITLE
hangs immediately after invoking

### ISSUE THREAD

**Issue by berzigaaraskog4** [the8thbit/e#6]
unfortunately 'e' hangs immediately after invoking. 

gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
Fedora release 26 (Twenty Six)
kernel: Linux XXX 4.12.13-300.fc26.x86_64

**Comment by the8thbit** [comment]
I'm experiencing the same issue on Windows Linux Subsystem... not sure why, I'll look into this, thanks.
